# Generated by Django 5.1.4 on 2024-12-22 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche')], max_length=1)),
                ('periode', models.CharField(choices=[('1', 'Matin'), ('2', 'Midi'), ('3', 'Aprem'), ('4', 'Soir')], max_length=1)),
                ('horaires', models.TextField()),
                ('nom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('6', 'Samedi'), ('7', 'Dimanche'), ('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi')], max_length=1)),
                ('legende', models.CharField(max_length=500)),
                ('lien', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='repenigmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_enigme', models.CharField(choices=[('3', 'Lundi'), ('4', 'Mardi'), ('5', 'Mercredi'), ('6', 'Jeudi'), ('7', 'Vendredi'), ('1', 'Samedi'), ('2', 'Dimanche')], max_length=1)),
                ('reponse', models.CharField(max_length=200)),
                ('indice', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='codeqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('datecreation', models.DateTimeField(auto_now_add=True)),
                ('dateutil', models.DateTimeField(blank=True, null=True)),
                ('points', models.IntegerField()),
                ('utilise', models.BooleanField()),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_utilisation', models.IntegerField(default=1)),
                ('lien', models.CharField(blank=True, max_length=100, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creat_codeqr', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_codeqr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enigme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_enigme', models.IntegerField()),
                ('reponse', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='histodinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defi', models.CharField(choices=[('1', 'Rembobiner'), ('2', 'Jura7Staff'), ('3', "Dans la peau d'un dino"), ('4', 'Eruption'), ('5', 'Clean my house'), ('6', 'Dompteur de dinos'), ('7', 'Instagraaaow'), ('8', 'Pro jura7'), ('9', 'Cruta7'), ('10', 'Herbivore confirmé'), ('11', 'Fictif'), ('12', 'Indiana Jaune'), ('13', 'Photosaure'), ('14', 'Jura-N7'), ('15', 'Camouflage'), ('16', "Le cri d'amour"), ('17', 'Les Dinoms'), ('18', 'Dino Train'), ('19', 'Dino di Caprio'), ('20', 'Cringeausaure'), ('21', 'Dinorigolo'), ('22', 'Photodino'), ('23', 'Cri au dino'), ('24', 'Surviva7'), ('25', 'Sa place est dans le musée'), ('26', 'Participation Rallye Colloc')], max_length=2)),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('beneficaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benf', to=settings.AUTH_USER_MODEL)),
                ('payeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mise', models.IntegerField()),
                ('gagnant', models.IntegerField()),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('avatar', models.TextField()),
                ('nomavatar', models.TextField(blank=True, null=True)),
                ('surnom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='achats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField()),
                ('nomavatar', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('surnom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
